version: '3.9'

networks:
  inventory:

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    tty: true
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - inventory

  mariadb:
    image: mariadb:latest
    container_name: database
    tty: true
    volumes:
      - ./docker/database:/var/lib/mysql:rw
      - ./docker/dump:/docker-entrypoint-initdb.d
    ports:
      - "4306:3606"
    depends_on:
      - nginx
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    networks:
      - inventory
  
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    tty: true
    volumes: 
      - ./app:/var/www/html
    ports:
      - "9000:80"
    networks:
      - inventory
